#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Select the status for the deactivated campaign response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum convert_campaign_response_deactivate_status
	{
		
		/// <summary>
		/// Closed Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 1,
		
		/// <summary>
		/// Cancelled Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 2,
	}
}
#pragma warning restore CS1591
