#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Select the type of sales entity which the campaign response should be converted to
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum convert_campaign_response_sales_entity_type
	{
		
		/// <summary>
		/// Opportunity Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 1,
		
		/// <summary>
		/// Order Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 2,
		
		/// <summary>
		/// Quote Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 3,
	}
}
#pragma warning restore CS1591
