#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// A Yes or No boolean.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum field_security_permission_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotAllowed = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allowed = 4,
	}
}
#pragma warning restore CS1591
