#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Sequence Step Sub Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_sequencestep_subtype
	{
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		/// <summary>
		/// LinkedIn Action Research Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInResearch = 1,
		
		/// <summary>
		/// LinkedIn Action Get Introduced Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInGetIntroduced = 2,
		
		/// <summary>
		/// LinkedIn Action Connect Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInConnect = 3,
		
		/// <summary>
		/// LinkedIn Action InMail Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInMail = 4,
		
		/// <summary>
		/// Advance To Other Sequence
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdvanceToOtherSequence = 5,
	}
}
#pragma warning restore CS1591
