#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Indicates the source of characteristic associated to the conversation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_conversationcharacteristicsource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RuleBased = 321240000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MLBased = 321240001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manual = 321240002,
	}
}
#pragma warning restore CS1591
