#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_panelstateoptions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Docked = 162450002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hidden = 162450001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Minimized = 162450000,
	}
}
#pragma warning restore CS1591
