#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Denotes the level of access a participant has in a conversation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_conversationaccesstype
	{
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		/// <summary>
		/// Public
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Public = 1,
		
		/// <summary>
		/// Private
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Private = 2,
	}
}
#pragma warning restore CS1591
