#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_actiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleDraftReview = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResolveCase = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailFollowup = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReplyToCustomer = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GatherIntentDetails = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SuggestResolution = 100000005,
	}
}
#pragma warning restore CS1591
