#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// This option set is used to list different Mapping Types.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_iotmappingtype
	{
		
		/// <summary>
		/// Map the device identifier.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deviceidentifier = 192350000,
		
		/// <summary>
		/// Map the rule identifier.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ruleidentifier = 192350001,
		
		/// <summary>
		/// Map a device property.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deviceproperty = 192350002,
	}
}
#pragma warning restore CS1591
