#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Whether this entity is tagged for solution harvesting or not.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_harvestingtag
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotRequired = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHarvesting = 192350001,
	}
}
#pragma warning restore CS1591
