#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Reason for the status of live conversation record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_conversation_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Waiting = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wrapup = 5,
	}
}
#pragma warning restore CS1591
