#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Time
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_playbookactivity_time
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0100AM = 100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0200AM = 200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0300AM = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0400AM = 400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0500AM = 500,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0600AM = 600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0700AM = 700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0800AM = 800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0900AM = 900,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1000AM = 1000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1100AM = 1100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1200PM = 1200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0100PM = 1300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0200PM = 1400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0300PM = 1500,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0400PM = 1600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0500PM = 1700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0600PM = 1800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0700PM = 1900,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0800PM = 2000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0900PM = 2100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1000PM = 2200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1100PM = 2300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1200AM = 0,
	}
}
#pragma warning restore CS1591
