#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Action to be taken due to overflow
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_overflowactiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 192350000,
		
		/// <summary>
		/// Close the conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EndConversation = 192350001,
		
		/// <summary>
		/// Transfer call to an external number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransfertoPhone = 192350002,
		
		/// <summary>
		/// Initiate callback for the customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectCallback = 192350003,
		
		/// <summary>
		/// Transfer call to voicemail
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicemail = 192350004,
		
		/// <summary>
		/// Transfer work item to another queue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueTransfer = 192350005,
		
		/// <summary>
		/// Keep work item waiting in queue for agent assignment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RemainInQueue = 192350006,
	}
}
#pragma warning restore CS1591
