#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// The set of allowed runtime types for parameter values
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyn_consoleapplicationparameterruntimetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@string = 110000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		number = 110000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		boolean = 110000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		json = 110000003,
	}
}
#pragma warning restore CS1591
