#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msdyncrm_imagepickerassetsproviders
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DigitalAssets = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Commerce = 2,
	}
}
#pragma warning restore CS1591
