#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Plot Option referenced by configuration.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum orginsightsconfiguration_plotoption
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Line = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Column = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Area = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pie = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bar = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Donut = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Infocard = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		List = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DoubleDonut = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinearGauge = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bubble = 11,
	}
}
#pragma warning restore CS1591
