#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Category of the process stage.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum processstage_category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Develop = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propose = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Identify = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approval = 7,
	}
}
#pragma warning restore CS1591
