#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Type of the system job.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum asyncoperation_operationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemEvent = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkEmail = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportFileParse = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransformParseData = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Import = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityPropagation = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateDetectionRulePublish = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDuplicateDetection = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SQMDataCollection = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickCampaign = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MatchcodeUpdate = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDelete = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletionService = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndexManagement = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CollectOrganizationStatistics = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSubprocess = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CalculateOrganizationStorageSize = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CollectOrganizationDatabaseStatistics = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CollectionOrganizationSizeStatistics = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DatabaseTuning = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CalculateOrganizationMaximumStorageSize = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDeleteSubprocess = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateStatisticIntervals = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationFullTextCatalogIndex = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Databaselogbackup = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateContractStates = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DBCCSHRINKDATABASEmaintenancejob = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DBCCSHRINKFILEmaintenancejob = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reindexallindicesmaintenancejob = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StorageLimitNotification = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cleanupinactiveworkflowassemblies = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringSeriesExpansion = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSampleData = 38,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GoalRollUp = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AuditPartitionCreation = 41,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CheckForLanguagePackUpdates = 42,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProvisionLanguagePack = 43,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateOrganizationDatabase = 44,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateSolution = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegenerateEntityRowCountSnapshotData = 46,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegenerateReadShareSnapshotData = 47,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutgoingActivity = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncomingEmailProcessing = 51,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailboxTestAccess = 52,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EncryptionHealthCheck = 53,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExecuteAsyncRequest = 54,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PosttoYammer = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateEntitlementStates = 56,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CalculateRollupField = 57,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MassCalculateRollupField = 58,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportTranslation = 59,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertDateAndTimeBehavior = 62,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityKeyIndexCreation = 63,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateKnowledgeArticleStates = 65,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceBookingSync = 68,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipAssistantCards = 69,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CleanupSolutionComponents = 71,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppModuleMetadataOperation = 72,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ALMAnomalyDetectionOperation = 73,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FlowNotification = 75,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonClientMetadataOperation = 76,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallbackRegistrationExpanderOperation = 79,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeAssign = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeDelete = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EventExpanderOperation = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSolutionMetadata = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDeleteFileAttachment = 94,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RefreshBusinessUnitforRecordsOwnedByPrincipal = 95,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RevokeInheritedAccess = 96,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Provisionlanguageforuser = 201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Migratenotestoattachmentsjob = 85,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Migratearticlecontenttofilestorage = 86,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdatedDeactivedOnforResolvedCasesjob = 87,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeReparentDBAsyncOperation = 88,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeMergeAsyncOperation = 89,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CreateOrRefreshVirtualEntity = 98,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExportSolutionAsyncOperation = 202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSolutionAsyncOperation = 203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PublishAllAsyncOperation = 204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeleteAndPromoteAsyncOperation = 207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UninstallSolutionAsyncOperation = 208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProvisionLanguageAsyncOperation = 209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportTranslationAsyncOperation = 210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StageAndUpgradeAsyncOperation = 211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DenormalizationAsyncOperation = 239,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RefreshRuntimeIntegrationComponentsAsyncOperation = 250,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeFlowSessionPermissionsAsyncOperation = 100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateModernFlowAsyncOperation = 101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AsyncArchiveAsyncOperation = 102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CancelAsyncOperations_System = 103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkArchiveOperation = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ArchiveExecutionAsyncOperation = 301,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinOpsDeploymentAsyncOperation = 302,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurgeArchivedContentOperation = 304,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegisterOfferingAsyncOperation = 305,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExecuteDataProcessingConfiguration = 306,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SyncSynapseTablesSchema = 307,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinOpsDBSyncAsyncOperation = 308,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinOpsUnitTestAsyncOperation = 309,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CatalogServiceGeneratePackageAsyncOperation = 320,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CatalogServiceSubmitApprovalRequestAsyncOperation = 321,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CatalogServiceInstallRequestAsyncOperation = 322,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TDSendpointprovisioningnewTVFfunctionsandgrantpermissionAsyncOperation = 330,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinOpsDeployCustomPackageAsyncOperation = 332,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletesrelatedElasticTablerecordswhenaSQLrecordisdeleted = 333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletesrelatedElasticorSQLTablerecordswhenanElasticTablerecordisdeleted = 334,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Catalogserviceasycoperationtopollforasolutioncheckerrequest = 335,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Catalogserviceasycoperationtosubmitasolutioncheckerrequest = 336,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Solutionserviceasyncoperationtoinstallsolutionafterappupdates = 337,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeAssignAllAsyncOperation = 105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BackgroundTeamServiceAsyncOperation = 106,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeGrantorRevokeAccessVersionTrackingAsyncOperation = 12801,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderTrainingEvents = 190690091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderPredictionEvents = 190690092,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessTableForRecycleBin = 104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AsyncRestoreJob = 187,
	}
	
	/// <summary>
	/// Status of the system job.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum asyncoperation_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ready = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suspended = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Locked = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 3,
	}
	
	/// <summary>
	/// Reason for the status of the system job.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum asyncoperation_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WaitingForResources = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Waiting = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pausing = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceling = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 32,
	}
	
	/// <summary>
	/// Process whose execution can proceed independently or in the background.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("asyncoperation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class AsyncOperation : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the asyncoperation entity
		/// </summary>
		public partial class Fields
		{
			public const string AsyncOperationId = "asyncoperationid";
			public const string Id = "asyncoperationid";
			public const string BreadcrumbId = "breadcrumbid";
			public const string CallerOrigin = "callerorigin";
			public const string CompletedOn = "completedon";
			public const string CorrelationId = "correlationid";
			public const string CorrelationUpdatedTime = "correlationupdatedtime";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string Data = "data";
			public const string DataBlobId = "datablobid";
			public const string DataBlobId_Name = "datablobid_name";
			public const string DependencyToken = "dependencytoken";
			public const string Depth = "depth";
			public const string ErrorCode = "errorcode";
			public const string ExecutionTimeSpan = "executiontimespan";
			public const string ExpanderStartTime = "expanderstarttime";
			public const string FriendlyMessage = "friendlymessage";
			public const string HostId = "hostid";
			public const string IsWaitingForEvent = "iswaitingforevent";
			public const string Message = "message";
			public const string MessageName = "messagename";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string Name = "name";
			public const string OperationType = "operationtype";
			public const string OperationTypeName = "operationtypename";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningExtensionId = "owningextensionid";
			public const string OwningExtensionIdName = "owningextensionidname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ParentPluginExecutionId = "parentpluginexecutionid";
			public const string PostponeUntil = "postponeuntil";
			public const string PrimaryEntityType = "primaryentitytype";
			public const string PrimaryEntityTypeName = "primaryentitytypename";
			public const string RecurrencePattern = "recurrencepattern";
			public const string RecurrenceStartTime = "recurrencestarttime";
			public const string RegardingObjectId = "regardingobjectid";
			public const string RegardingObjectIdName = "regardingobjectidname";
			public const string RegardingObjectIdYomiName = "regardingobjectidyominame";
			public const string RequestId = "requestid";
			public const string RetainJobHistory = "retainjobhistory";
			public const string RetryCount = "retrycount";
			public const string RootExecutionContext = "rootexecutioncontext";
			public const string Sequence = "sequence";
			public const string StartedOn = "startedon";
			public const string StateCode = "statecode";
			public const string StateCodeName = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodeName = "statuscodename";
			public const string Subtype = "subtype";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string WorkflowActivationId = "workflowactivationid";
			public const string WorkflowActivationIdName = "workflowactivationidname";
			public const string WorkflowStageName = "workflowstagename";
			public const string Workload = "workload";
			public const string AsyncOperation_Emails = "AsyncOperation_Emails";
			public const string Account_AsyncOperations = "Account_AsyncOperations";
			public const string ActivityPointer_AsyncOperations = "ActivityPointer_AsyncOperations";
			public const string Annotation_AsyncOperations = "Annotation_AsyncOperations";
			public const string business_unit_asyncoperation = "business_unit_asyncoperation";
			public const string BusinessUnit_AsyncOperations = "BusinessUnit_AsyncOperations";
			public const string Connection_AsyncOperations = "Connection_AsyncOperations";
			public const string Contact_AsyncOperations = "Contact_AsyncOperations";
			public const string Contract_AsyncOperations = "Contract_AsyncOperations";
			public const string Email_AsyncOperations = "Email_AsyncOperations";
			public const string Fax_AsyncOperations = "Fax_AsyncOperations";
			public const string Incident_AsyncOperations = "Incident_AsyncOperations";
			public const string IncidentResolution_AsyncOperations = "IncidentResolution_AsyncOperations";
			public const string Lead_AsyncOperations = "Lead_AsyncOperations";
			public const string List_AsyncOperations = "List_AsyncOperations";
			public const string listmember_AsyncOperations = "listmember_AsyncOperations";
			public const string lk_asyncoperation_createdby = "lk_asyncoperation_createdby";
			public const string lk_asyncoperation_createdonbehalfby = "lk_asyncoperation_createdonbehalfby";
			public const string lk_asyncoperation_modifiedby = "lk_asyncoperation_modifiedby";
			public const string lk_asyncoperation_modifiedonbehalfby = "lk_asyncoperation_modifiedonbehalfby";
			public const string lk_asyncoperation_workflowactivationid = "lk_asyncoperation_workflowactivationid";
			public const string Opportunity_AsyncOperations = "Opportunity_AsyncOperations";
			public const string OpportunityClose_AsyncOperations = "OpportunityClose_AsyncOperations";
			public const string Organization_AsyncOperations = "Organization_AsyncOperations";
			public const string PhoneCall_AsyncOperations = "PhoneCall_AsyncOperations";
			public const string Queue_AsyncOperations = "Queue_AsyncOperations";
			public const string QueueItem_AsyncOperations = "QueueItem_AsyncOperations";
			public const string Quote_AsyncOperations = "Quote_AsyncOperations";
			public const string SdkMessageProcessingStep_AsyncOperations = "SdkMessageProcessingStep_AsyncOperations";
			public const string system_user_asyncoperation = "system_user_asyncoperation";
			public const string SystemUser_AsyncOperations = "SystemUser_AsyncOperations";
			public const string Task_AsyncOperations = "Task_AsyncOperations";
			public const string team_asyncoperation = "team_asyncoperation";
			public const string Team_AsyncOperations = "Team_AsyncOperations";
			public const string Template_AsyncOperations = "Template_AsyncOperations";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public AsyncOperation() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "asyncoperation";
		
		public const string EntityLogicalCollectionName = "asyncoperations";
		
		public const string EntitySetName = "asyncoperations";
		
		public const int EntityTypeCode = 4700;
		
		/// <summary>
		/// Unique identifier of the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asyncoperationid")]
		public System.Nullable<System.Guid> AsyncOperationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("asyncoperationid");
			}
			set
			{
				this.SetAttributeValue("asyncoperationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asyncoperationid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.AsyncOperationId = value;
			}
		}
		
		/// <summary>
		/// The breadcrumb record ID.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("breadcrumbid")]
		public System.Nullable<System.Guid> BreadcrumbId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("breadcrumbid");
			}
			set
			{
				this.SetAttributeValue("breadcrumbid", value);
			}
		}
		
		/// <summary>
		/// The origin of the caller.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("callerorigin")]
		public string CallerOrigin
		{
			get
			{
				return this.GetAttributeValue<string>("callerorigin");
			}
			set
			{
				this.SetAttributeValue("callerorigin", value);
			}
		}
		
		/// <summary>
		/// Date and time when the system job was completed.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("completedon")]
		public System.Nullable<System.DateTime> CompletedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("completedon");
			}
		}
		
		/// <summary>
		/// Unique identifier used to correlate between multiple SDK requests and system jobs.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("correlationid")]
		public System.Nullable<System.Guid> CorrelationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("correlationid");
			}
			set
			{
				this.SetAttributeValue("correlationid", value);
			}
		}
		
		/// <summary>
		/// Last time the correlation depth was updated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("correlationupdatedtime")]
		public System.Nullable<System.DateTime> CorrelationUpdatedTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("correlationupdatedtime");
			}
			set
			{
				this.SetAttributeValue("correlationupdatedtime", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the system job was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the asyncoperation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unstructured data associated with the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("data")]
		public string Data
		{
			get
			{
				return this.GetAttributeValue<string>("data");
			}
			set
			{
				this.SetAttributeValue("data", value);
			}
		}
		
		/// <summary>
		/// File Id for the blob url used for file storage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datablobid")]
		public object DataBlobId
		{
			get
			{
				return this.GetAttributeValue<object>("datablobid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datablobid_name")]
		public string DataBlobId_Name
		{
			get
			{
				if (this.FormattedValues.Contains("datablobid"))
				{
					return this.FormattedValues["datablobid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Execution of all operations with the same dependency token is serialized.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencytoken")]
		public string DependencyToken
		{
			get
			{
				return this.GetAttributeValue<string>("dependencytoken");
			}
			set
			{
				this.SetAttributeValue("dependencytoken", value);
			}
		}
		
		/// <summary>
		/// Number of SDK calls made since the first call.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("depth")]
		public System.Nullable<int> Depth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("depth");
			}
			set
			{
				this.SetAttributeValue("depth", value);
			}
		}
		
		/// <summary>
		/// Error code returned from a canceled system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("errorcode")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("errorcode");
			}
		}
		
		/// <summary>
		/// Time that the system job has taken to execute.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("executiontimespan")]
		public System.Nullable<double> ExecutionTimeSpan
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("executiontimespan");
			}
		}
		
		/// <summary>
		/// The datetime when the Expander pipeline started.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expanderstarttime")]
		public System.Nullable<System.DateTime> ExpanderStartTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("expanderstarttime");
			}
			set
			{
				this.SetAttributeValue("expanderstarttime", value);
			}
		}
		
		/// <summary>
		/// Message provided by the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("friendlymessage")]
		public string FriendlyMessage
		{
			get
			{
				return this.GetAttributeValue<string>("friendlymessage");
			}
			set
			{
				this.SetAttributeValue("friendlymessage", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the host that owns this system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("hostid")]
		public string HostId
		{
			get
			{
				return this.GetAttributeValue<string>("hostid");
			}
			set
			{
				this.SetAttributeValue("hostid", value);
			}
		}
		
		/// <summary>
		/// Indicates that the system job is waiting for an event.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iswaitingforevent")]
		public System.Nullable<bool> IsWaitingForEvent
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("iswaitingforevent");
			}
		}
		
		/// <summary>
		/// Message related to the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("message")]
		public string Message
		{
			get
			{
				return this.GetAttributeValue<string>("message");
			}
		}
		
		/// <summary>
		/// Name of the message that started this system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("messagename")]
		public string MessageName
		{
			get
			{
				return this.GetAttributeValue<string>("messagename");
			}
			set
			{
				this.SetAttributeValue("messagename", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Name of the user who last modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// YomiName of the user who last modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the system job was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the asyncoperation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Name of the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Type of the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("operationtype")]
		public virtual asyncoperation_operationtype? OperationType
		{
			get
			{
				return ((asyncoperation_operationtype?)(EntityOptionSetEnum.GetEnum(this, "operationtype")));
			}
			set
			{
				this.SetAttributeValue("operationtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Describes the record type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("operationtypename")]
		public string OperationTypeName
		{
			get
			{
				if (this.FormattedValues.Contains("operationtype"))
				{
					return this.FormattedValues["operationtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit that owns the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the owning extension with which the system job is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningextensionid")]
		public Microsoft.Xrm.Sdk.EntityReference OwningExtensionId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningextensionid");
			}
			set
			{
				this.SetAttributeValue("owningextensionid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningextensionidname")]
		public string OwningExtensionIdName
		{
			get
			{
				if (this.FormattedValues.Contains("owningextensionid"))
				{
					return this.FormattedValues["owningextensionid"];
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.SetAttributeValue("owningextensionidname", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the team who owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentpluginexecutionid")]
		public System.Nullable<System.Guid> ParentPluginExecutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("parentpluginexecutionid");
			}
			set
			{
				this.SetAttributeValue("parentpluginexecutionid", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the system job should run only after the specified date and time.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("postponeuntil")]
		public System.Nullable<System.DateTime> PostponeUntil
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("postponeuntil");
			}
			set
			{
				this.SetAttributeValue("postponeuntil", value);
			}
		}
		
		/// <summary>
		/// Type of entity with which the system job is primarily associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryentitytype")]
		public string PrimaryEntityType
		{
			get
			{
				return this.GetAttributeValue<string>("primaryentitytype");
			}
			set
			{
				this.SetAttributeValue("primaryentitytype", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryentitytypename")]
		public string PrimaryEntityTypeName
		{
			get
			{
				if (this.FormattedValues.Contains("primaryentitytype"))
				{
					return this.FormattedValues["primaryentitytype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Pattern of the system job's recurrence.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("recurrencepattern")]
		public string RecurrencePattern
		{
			get
			{
				return this.GetAttributeValue<string>("recurrencepattern");
			}
			set
			{
				this.SetAttributeValue("recurrencepattern", value);
			}
		}
		
		/// <summary>
		/// Starting time in UTC for the recurrence pattern.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("recurrencestarttime")]
		public System.Nullable<System.DateTime> RecurrenceStartTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("recurrencestarttime");
			}
			set
			{
				this.SetAttributeValue("recurrencestarttime", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the object with which the system job is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		public Microsoft.Xrm.Sdk.EntityReference RegardingObjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("regardingobjectid");
			}
			set
			{
				this.SetAttributeValue("regardingobjectid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectidname")]
		public string RegardingObjectIdName
		{
			get
			{
				if (this.FormattedValues.Contains("regardingobjectid"))
				{
					return this.FormattedValues["regardingobjectid"];
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.SetAttributeValue("regardingobjectidname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectidyominame")]
		public string RegardingObjectIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("regardingobjectid"))
				{
					return this.FormattedValues["regardingobjectid"];
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.SetAttributeValue("regardingobjectidyominame", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the request that generated the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requestid")]
		public System.Nullable<System.Guid> RequestId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("requestid");
			}
			set
			{
				this.SetAttributeValue("requestid", value);
			}
		}
		
		/// <summary>
		/// Retain job history.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("retainjobhistory")]
		public System.Nullable<bool> RetainJobHistory
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("retainjobhistory");
			}
			set
			{
				this.SetAttributeValue("retainjobhistory", value);
			}
		}
		
		/// <summary>
		/// Number of times to retry the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("retrycount")]
		public System.Nullable<int> RetryCount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("retrycount");
			}
		}
		
		/// <summary>
		/// Root execution context of the job that trigerred async job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rootexecutioncontext")]
		public string RootExecutionContext
		{
			get
			{
				return this.GetAttributeValue<string>("rootexecutioncontext");
			}
			set
			{
				this.SetAttributeValue("rootexecutioncontext", value);
			}
		}
		
		/// <summary>
		/// Order in which operations were submitted.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sequence")]
		public System.Nullable<long> Sequence
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("sequence");
			}
		}
		
		/// <summary>
		/// Date and time when the system job was started.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("startedon")]
		public System.Nullable<System.DateTime> StartedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("startedon");
			}
		}
		
		/// <summary>
		/// Status of the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual asyncoperation_statecode? StateCode
		{
			get
			{
				return ((asyncoperation_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// State name of the async operation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual asyncoperation_statuscode? StatusCode
		{
			get
			{
				return ((asyncoperation_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The Subtype of the Async Job
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subtype")]
		public System.Nullable<int> Subtype
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("subtype");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the workflow activation related to the system job.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowactivationid")]
		public Microsoft.Xrm.Sdk.EntityReference WorkflowActivationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("workflowactivationid");
			}
			set
			{
				this.SetAttributeValue("workflowactivationid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowactivationidname")]
		public string WorkflowActivationIdName
		{
			get
			{
				if (this.FormattedValues.Contains("workflowactivationid"))
				{
					return this.FormattedValues["workflowactivationid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Name of a workflow stage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowstagename")]
		public string WorkflowStageName
		{
			get
			{
				return this.GetAttributeValue<string>("workflowstagename");
			}
		}
		
		/// <summary>
		/// The workload name.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workload")]
		public string Workload
		{
			get
			{
				return this.GetAttributeValue<string>("workload");
			}
			set
			{
				this.SetAttributeValue("workload", value);
			}
		}
		
		/// <summary>
		/// 1:N AsyncOperation_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("AsyncOperation_Emails")]
		public System.Collections.Generic.IEnumerable<DataverseEntities.Email> AsyncOperation_Emails
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.Email>("AsyncOperation_Emails", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.Email>("AsyncOperation_Emails", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Account_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Account_AsyncOperations")]
		public DataverseEntities.Account Account_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Account>("Account_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Account>("Account_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ActivityPointer_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ActivityPointer_AsyncOperations")]
		public DataverseEntities.ActivityPointer ActivityPointer_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.ActivityPointer>("ActivityPointer_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.ActivityPointer>("ActivityPointer_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Annotation_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Annotation_AsyncOperations")]
		public DataverseEntities.Annotation Annotation_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Annotation>("Annotation_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Annotation>("Annotation_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_asyncoperation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_asyncoperation")]
		public DataverseEntities.BusinessUnit business_unit_asyncoperation
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.BusinessUnit>("business_unit_asyncoperation", null);
			}
		}
		
		/// <summary>
		/// N:1 BusinessUnit_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("BusinessUnit_AsyncOperations")]
		public DataverseEntities.BusinessUnit BusinessUnit_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.BusinessUnit>("BusinessUnit_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.BusinessUnit>("BusinessUnit_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Connection_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Connection_AsyncOperations")]
		public DataverseEntities.Connection Connection_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Connection>("Connection_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Connection>("Connection_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Contact_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contact_AsyncOperations")]
		public DataverseEntities.Contact Contact_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Contact>("Contact_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Contact>("Contact_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Contract_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contract_AsyncOperations")]
		public DataverseEntities.Contract Contract_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Contract>("Contract_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Contract>("Contract_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Email_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Email_AsyncOperations")]
		public DataverseEntities.Email Email_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Email>("Email_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Email>("Email_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Fax_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Fax_AsyncOperations")]
		public DataverseEntities.Fax Fax_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Fax>("Fax_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Fax>("Fax_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Incident_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Incident_AsyncOperations")]
		public DataverseEntities.Incident Incident_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Incident>("Incident_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Incident>("Incident_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 IncidentResolution_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("IncidentResolution_AsyncOperations")]
		public DataverseEntities.IncidentResolution IncidentResolution_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.IncidentResolution>("IncidentResolution_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.IncidentResolution>("IncidentResolution_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Lead_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Lead_AsyncOperations")]
		public DataverseEntities.Lead Lead_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Lead>("Lead_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Lead>("Lead_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 List_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("List_AsyncOperations")]
		public DataverseEntities.List List_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.List>("List_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.List>("List_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 listmember_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("listmember_AsyncOperations")]
		public DataverseEntities.ListMember listmember_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.ListMember>("listmember_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.ListMember>("listmember_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_asyncoperation_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_asyncoperation_createdby")]
		public DataverseEntities.SystemUser lk_asyncoperation_createdby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("lk_asyncoperation_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_asyncoperation_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_asyncoperation_createdonbehalfby")]
		public DataverseEntities.SystemUser lk_asyncoperation_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("lk_asyncoperation_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_asyncoperation_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_asyncoperation_modifiedby")]
		public DataverseEntities.SystemUser lk_asyncoperation_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("lk_asyncoperation_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_asyncoperation_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_asyncoperation_modifiedonbehalfby")]
		public DataverseEntities.SystemUser lk_asyncoperation_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("lk_asyncoperation_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_asyncoperation_workflowactivationid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowactivationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_asyncoperation_workflowactivationid")]
		public DataverseEntities.Workflow lk_asyncoperation_workflowactivationid
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Workflow>("lk_asyncoperation_workflowactivationid", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Workflow>("lk_asyncoperation_workflowactivationid", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Opportunity_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Opportunity_AsyncOperations")]
		public DataverseEntities.Opportunity Opportunity_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Opportunity>("Opportunity_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Opportunity>("Opportunity_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 OpportunityClose_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("OpportunityClose_AsyncOperations")]
		public DataverseEntities.OpportunityClose OpportunityClose_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.OpportunityClose>("OpportunityClose_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.OpportunityClose>("OpportunityClose_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Organization_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Organization_AsyncOperations")]
		public DataverseEntities.Organization Organization_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Organization>("Organization_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Organization>("Organization_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 PhoneCall_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("PhoneCall_AsyncOperations")]
		public DataverseEntities.PhoneCall PhoneCall_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.PhoneCall>("PhoneCall_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.PhoneCall>("PhoneCall_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Queue_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Queue_AsyncOperations")]
		public DataverseEntities.Queue Queue_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Queue>("Queue_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Queue>("Queue_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 QueueItem_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("QueueItem_AsyncOperations")]
		public DataverseEntities.QueueItem QueueItem_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.QueueItem>("QueueItem_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.QueueItem>("QueueItem_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Quote_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Quote_AsyncOperations")]
		public DataverseEntities.Quote Quote_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Quote>("Quote_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Quote>("Quote_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 SdkMessageProcessingStep_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningextensionid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SdkMessageProcessingStep_AsyncOperations")]
		public DataverseEntities.SdkMessageProcessingStep SdkMessageProcessingStep_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SdkMessageProcessingStep>("SdkMessageProcessingStep_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.SdkMessageProcessingStep>("SdkMessageProcessingStep_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 system_user_asyncoperation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("system_user_asyncoperation")]
		public DataverseEntities.SystemUser system_user_asyncoperation
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("system_user_asyncoperation", null);
			}
		}
		
		/// <summary>
		/// N:1 SystemUser_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SystemUser_AsyncOperations")]
		public DataverseEntities.SystemUser SystemUser_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("SystemUser_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.SystemUser>("SystemUser_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Task_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Task_AsyncOperations")]
		public DataverseEntities.Task Task_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Task>("Task_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Task>("Task_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 team_asyncoperation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_asyncoperation")]
		public DataverseEntities.Team team_asyncoperation
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Team>("team_asyncoperation", null);
			}
		}
		
		/// <summary>
		/// N:1 Team_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Team_AsyncOperations")]
		public DataverseEntities.Team Team_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Team>("Team_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Team>("Team_AsyncOperations", null, value);
			}
		}
		
		/// <summary>
		/// N:1 Template_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Template_AsyncOperations")]
		public DataverseEntities.Template Template_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Template>("Template_AsyncOperations", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Template>("Template_AsyncOperations", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
