#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// Business Process Type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_businessprocesstype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessFlow = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaskFlow = 1,
	}
	
	/// <summary>
	/// Category of the process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dialog = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessRule = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Action = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessProcessFlow = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModernFlow = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DesktopFlow = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIFlow = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebClientAPIFlow = 9000,
	}
	
	/// <summary>
	/// Mode of the process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_mode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Background = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Realtime = 1,
	}
	
	/// <summary>
	/// Type of the Modern Flow process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_modernflowtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerAutomateFlow = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotStudioFlow = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum processtrigger_scope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Form = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 2,
	}
	
	/// <summary>
	/// Workflow scope.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_scope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessUnit = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ParentChildBusinessUnits = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 4,
	}
	
	/// <summary>
	/// Status of the workflow
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suspended = 2,
	}
	
	/// <summary>
	/// Reason for the status of the workflow
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activated = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompanyDLPViolation = 3,
	}
	
	/// <summary>
	/// Type of workflow throttling behavior.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_throttlingbehaviortype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TenantPool = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotStudio = 2,
	}
	
	/// <summary>
	/// Workflow type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Definition = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activation = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Template = 3,
	}
	
	/// <summary>
	/// Type of the UI Flow process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum workflow_uiflowtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Windowsrecorder_V1 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SeleniumIDE = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerAutomateDesktop = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Test = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recording = 101,
	}
	
	/// <summary>
	/// Set of logical rules that define the steps necessary to automate a specific business process, task, or set of actions to be performed.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("workflow")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class Workflow : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the workflow entity
		/// </summary>
		public partial class Fields
		{
			public const string ActiveWorkflowId = "activeworkflowid";
			public const string ActiveWorkflowIdName = "activeworkflowidname";
			public const string AsyncAutoDelete = "asyncautodelete";
			public const string AsyncAutoDeleteName = "asyncautodeletename";
			public const string BillingContext = "billingcontext";
			public const string BusinessProcessType = "businessprocesstype";
			public const string BusinessProcessTypeName = "businessprocesstypename";
			public const string Category = "category";
			public const string CategoryName = "categoryname";
			public const string Claims = "claims";
			public const string ClientData = "clientdata";
			public const string ClientDataIsCompressed = "clientdataiscompressed";
			public const string clientdataiscompressedName = "clientdataiscompressedname";
			public const string ComponentState = "componentstate";
			public const string ConnectionReferences = "connectionreferences";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string CreateMetadata = "createmetadata";
			public const string CreateStage = "createstage";
			public const string CreateStageName = "createstagename";
			public const string Credentials = "credentials";
			public const string Definition = "definition";
			public const string DeleteStage = "deletestage";
			public const string DeleteStageName = "deletestagename";
			public const string Dependencies = "dependencies";
			public const string Description = "description";
			public const string DesktopFlowModules = "desktopflowmodules";
			public const string DynamicsSolutionContext = "dynamicssolutioncontext";
			public const string EntityImage = "entityimage";
			public const string EntityImage_Timestamp = "entityimage_timestamp";
			public const string EntityImage_URL = "entityimage_url";
			public const string EntityImageId = "entityimageid";
			public const string FormId = "formid";
			public const string InputParameters = "inputparameters";
			public const string Inputs = "inputs";
			public const string IntroducedVersion = "introducedversion";
			public const string IsCrmUIWorkflow = "iscrmuiworkflow";
			public const string IsCustomizable = "iscustomizable";
			public const string IsCustomProcessingStepAllowedForOtherPublishers = "iscustomprocessingstepallowedforotherpublishers";
			public const string IsManaged = "ismanaged";
			public const string IsManagedName = "ismanagedname";
			public const string IsTransacted = "istransacted";
			public const string IsTransactedName = "istransactedname";
			public const string LanguageCode = "languagecode";
			public const string LicenseEntitledBy = "licenseentitledby";
			public const string licenseentitledbyName = "licenseentitledbyname";
			public const string Metadata = "metadata";
			public const string Mode = "mode";
			public const string ModeName = "modename";
			public const string ModernFlowType = "modernflowtype";
			public const string modernflowtypeName = "modernflowtypename";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string ModifyMetadata = "modifymetadata";
			public const string Name = "name";
			public const string OnDemand = "ondemand";
			public const string OnDemandName = "ondemandname";
			public const string Outputs = "outputs";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ParentWorkflowId = "parentworkflowid";
			public const string ParentWorkflowIdName = "parentworkflowidname";
			public const string PlanVerified = "planverified";
			public const string planverifiedName = "planverifiedname";
			public const string PluginTypeId = "plugintypeid";
			public const string PrimaryEntity = "primaryentity";
			public const string PrimaryEntityName = "primaryentityname";
			public const string ProcessOrder = "processorder";
			public const string ProcessRoleAssignment = "processroleassignment";
			public const string ProcessTriggerFormId = "processtriggerformid";
			public const string ProcessTriggerScope = "processtriggerscope";
			public const string ProcessTriggerScopeName = "processtriggerscopename";
			public const string Rank = "rank";
			public const string RendererObjectTypeCode = "rendererobjecttypecode";
			public const string ResourceContainer = "resourcecontainer";
			public const string ResourceId = "resourceid";
			public const string RunAs = "runas";
			public const string RunAsName = "runasname";
			public const string SchemaVersion = "schemaversion";
			public const string Scope = "scope";
			public const string ScopeName = "scopename";
			public const string SdkMessageId = "sdkmessageid";
			public const string SolutionId = "solutionid";
			public const string StateCode = "statecode";
			public const string StateCodeName = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodeName = "statuscodename";
			public const string Subprocess = "subprocess";
			public const string SubprocessName = "subprocessname";
			public const string SuspensionReasonDetails = "suspensionreasondetails";
			public const string SyncWorkflowLogOnFailure = "syncworkflowlogonfailure";
			public const string SyncWorkflowLogOnFailureName = "syncworkflowlogonfailurename";
			public const string ThrottlingBehavior = "throttlingbehavior";
			public const string throttlingbehaviorName = "throttlingbehaviorname";
			public const string TriggerOnCreate = "triggeroncreate";
			public const string TriggerOnCreateName = "triggeroncreatename";
			public const string TriggerOnDelete = "triggerondelete";
			public const string TriggerOnDeleteName = "triggerondeletename";
			public const string TriggerOnUpdateAttributeList = "triggeronupdateattributelist";
			public const string TrustedAccess = "trustedaccess";
			public const string trustedaccessName = "trustedaccessname";
			public const string Type = "type";
			public const string TypeName = "typename";
			public const string UIData = "uidata";
			public const string UIFlowType = "uiflowtype";
			public const string UIFlowTypeName = "uiflowtypename";
			public const string UniqueName = "uniquename";
			public const string UpdateStage = "updatestage";
			public const string UpdateStageName = "updatestagename";
			public const string VersionNumber = "versionnumber";
			public const string WorkflowId = "workflowid";
			public const string Id = "workflowid";
			public const string WorkflowIdUnique = "workflowidunique";
			public const string Xaml = "xaml";
			public const string lk_asyncoperation_workflowactivationid = "lk_asyncoperation_workflowactivationid";
			public const string lk_processsession_processid = "lk_processsession_processid";
			public const string process_processstage = "process_processstage";
			public const string Referencedworkflow_active_workflow = "Referencedworkflow_active_workflow";
			public const string Workflow_Annotation = "Workflow_Annotation";
			public const string ReferencedWorkflow_licenseentitledby = "ReferencedWorkflow_licenseentitledby";
			public const string Referencedworkflow_parent_workflow = "Referencedworkflow_parent_workflow";
			public const string business_unit_workflow = "business_unit_workflow";
			public const string system_user_workflow = "system_user_workflow";
			public const string team_workflow = "team_workflow";
			public const string Referencingworkflow_active_workflow = "workflow_active_workflow";
			public const string workflow_createdby = "workflow_createdby";
			public const string workflow_createdonbehalfby = "workflow_createdonbehalfby";
			public const string ReferencingWorkflow_licenseentitledby = "Workflow_licenseentitledby";
			public const string workflow_modifiedby = "workflow_modifiedby";
			public const string workflow_modifiedonbehalfby = "workflow_modifiedonbehalfby";
			public const string Referencingworkflow_parent_workflow = "workflow_parent_workflow";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Workflow() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "workflow";
		
		public const string EntityLogicalCollectionName = "workflows";
		
		public const string EntitySetName = "workflows";
		
		public const int EntityTypeCode = 4703;
		
		/// <summary>
		/// Unique identifier of the latest activation record for the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activeworkflowid")]
		public Microsoft.Xrm.Sdk.EntityReference ActiveWorkflowId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("activeworkflowid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activeworkflowidname")]
		public string ActiveWorkflowIdName
		{
			get
			{
				if (this.FormattedValues.Contains("activeworkflowid"))
				{
					return this.FormattedValues["activeworkflowid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Indicates whether the asynchronous system job is automatically deleted on completion.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asyncautodelete")]
		public System.Nullable<bool> AsyncAutoDelete
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("asyncautodelete");
			}
			set
			{
				this.SetAttributeValue("asyncautodelete", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asyncautodeletename")]
		public string AsyncAutoDeleteName
		{
			get
			{
				if (this.FormattedValues.Contains("asyncautodelete"))
				{
					return this.FormattedValues["asyncautodelete"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Billing context this flow is in.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billingcontext")]
		public string BillingContext
		{
			get
			{
				return this.GetAttributeValue<string>("billingcontext");
			}
			set
			{
				this.SetAttributeValue("billingcontext", value);
			}
		}
		
		/// <summary>
		/// Business Process Type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessprocesstype")]
		public virtual workflow_businessprocesstype? BusinessProcessType
		{
			get
			{
				return ((workflow_businessprocesstype?)(EntityOptionSetEnum.GetEnum(this, "businessprocesstype")));
			}
			set
			{
				this.SetAttributeValue("businessprocesstype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessprocesstypename")]
		public string BusinessProcessTypeName
		{
			get
			{
				if (this.FormattedValues.Contains("businessprocesstype"))
				{
					return this.FormattedValues["businessprocesstype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Category of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("category")]
		public virtual workflow_category? Category
		{
			get
			{
				return ((workflow_category?)(EntityOptionSetEnum.GetEnum(this, "category")));
			}
			set
			{
				this.SetAttributeValue("category", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("categoryname")]
		public string CategoryName
		{
			get
			{
				if (this.FormattedValues.Contains("category"))
				{
					return this.FormattedValues["category"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Claims related to this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("claims")]
		public string Claims
		{
			get
			{
				return this.GetAttributeValue<string>("claims");
			}
			set
			{
				this.SetAttributeValue("claims", value);
			}
		}
		
		/// <summary>
		/// Business logic converted into client data
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clientdata")]
		public string ClientData
		{
			get
			{
				return this.GetAttributeValue<string>("clientdata");
			}
			set
			{
				this.SetAttributeValue("clientdata", value);
			}
		}
		
		/// <summary>
		/// For Internal Use Only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clientdataiscompressed")]
		public System.Nullable<bool> ClientDataIsCompressed
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("clientdataiscompressed");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clientdataiscompressedname")]
		public string clientdataiscompressedName
		{
			get
			{
				if (this.FormattedValues.Contains("clientdataiscompressed"))
				{
					return this.FormattedValues["clientdataiscompressed"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Connection References related to this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionreferences")]
		public string ConnectionReferences
		{
			get
			{
				return this.GetAttributeValue<string>("connectionreferences");
			}
			set
			{
				this.SetAttributeValue("connectionreferences", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the process was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Create metadata for this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createmetadata")]
		public string CreateMetadata
		{
			get
			{
				return this.GetAttributeValue<string>("createmetadata");
			}
			set
			{
				this.SetAttributeValue("createmetadata", value);
			}
		}
		
		/// <summary>
		/// Stage of the process when triggered on Create.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createstage")]
		public virtual workflow_stage? CreateStage
		{
			get
			{
				return ((workflow_stage?)(EntityOptionSetEnum.GetEnum(this, "createstage")));
			}
			set
			{
				this.SetAttributeValue("createstage", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createstagename")]
		public string CreateStageName
		{
			get
			{
				if (this.FormattedValues.Contains("createstage"))
				{
					return this.FormattedValues["createstage"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Credentials related to this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("credentials")]
		public string Credentials
		{
			get
			{
				return this.GetAttributeValue<string>("credentials");
			}
			set
			{
				this.SetAttributeValue("credentials", value);
			}
		}
		
		/// <summary>
		/// Definition of the business logic of this workflow instance.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("definition")]
		public string Definition
		{
			get
			{
				return this.GetAttributeValue<string>("definition");
			}
			set
			{
				this.SetAttributeValue("definition", value);
			}
		}
		
		/// <summary>
		/// Stage of the process when triggered on Delete.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deletestage")]
		public virtual workflow_stage? DeleteStage
		{
			get
			{
				return ((workflow_stage?)(EntityOptionSetEnum.GetEnum(this, "deletestage")));
			}
			set
			{
				this.SetAttributeValue("deletestage", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deletestagename")]
		public string DeleteStageName
		{
			get
			{
				if (this.FormattedValues.Contains("deletestage"))
				{
					return this.FormattedValues["deletestage"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Soft dependencies of this workflow instance.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencies")]
		public string Dependencies
		{
			get
			{
				return this.GetAttributeValue<string>("dependencies");
			}
			set
			{
				this.SetAttributeValue("dependencies", value);
			}
		}
		
		/// <summary>
		/// Description of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Desktop flow modules related to this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("desktopflowmodules")]
		public string DesktopFlowModules
		{
			get
			{
				return this.GetAttributeValue<string>("desktopflowmodules");
			}
			set
			{
				this.SetAttributeValue("desktopflowmodules", value);
			}
		}
		
		/// <summary>
		/// comma separated list of one or more Dynamics First Party Solution Unique names that this workflow is in context of.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dynamicssolutioncontext")]
		public string DynamicsSolutionContext
		{
			get
			{
				return this.GetAttributeValue<string>("dynamicssolutioncontext");
			}
			set
			{
				this.SetAttributeValue("dynamicssolutioncontext", value);
			}
		}
		
		/// <summary>
		/// Shows the default image for the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			set
			{
				this.SetAttributeValue("entityimage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated form.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("formid")]
		public System.Nullable<System.Guid> FormId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("formid");
			}
			set
			{
				this.SetAttributeValue("formid", value);
			}
		}
		
		/// <summary>
		/// Input parameters to the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("inputparameters")]
		public string InputParameters
		{
			get
			{
				return this.GetAttributeValue<string>("inputparameters");
			}
			set
			{
				this.SetAttributeValue("inputparameters", value);
			}
		}
		
		/// <summary>
		/// Inputs definition for this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("inputs")]
		public string Inputs
		{
			get
			{
				return this.GetAttributeValue<string>("inputs");
			}
			set
			{
				this.SetAttributeValue("inputs", value);
			}
		}
		
		/// <summary>
		/// Version in which the form is introduced.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.SetAttributeValue("introducedversion", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the process was created using the Microsoft Dynamics 365 Web application.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscrmuiworkflow")]
		public System.Nullable<bool> IsCrmUIWorkflow
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("iscrmuiworkflow");
			}
		}
		
		/// <summary>
		/// Information that specifies whether this component can be customized.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.SetAttributeValue("iscustomizable", value);
			}
		}
		
		/// <summary>
		/// Defines whether other publishers can attach custom processing steps to this action
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomprocessingstepallowedforotherpublishers")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomProcessingStepAllowedForOtherPublishers
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomprocessingstepallowedforotherpublishers");
			}
			set
			{
				this.SetAttributeValue("iscustomprocessingstepallowedforotherpublishers", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanagedname")]
		public string IsManagedName
		{
			get
			{
				if (this.FormattedValues.Contains("ismanaged"))
				{
					return this.FormattedValues["ismanaged"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Whether or not the steps in the process are executed in a single transaction.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("istransacted")]
		public System.Nullable<bool> IsTransacted
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("istransacted");
			}
			set
			{
				this.SetAttributeValue("istransacted", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("istransactedname")]
		public string IsTransactedName
		{
			get
			{
				if (this.FormattedValues.Contains("istransacted"))
				{
					return this.FormattedValues["istransacted"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Language of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languagecode")]
		public System.Nullable<int> LanguageCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("languagecode");
			}
			set
			{
				this.SetAttributeValue("languagecode", value);
			}
		}
		
		/// <summary>
		/// The source of the license entitlements.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("licenseentitledby")]
		public Microsoft.Xrm.Sdk.EntityReference LicenseEntitledBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("licenseentitledby");
			}
			set
			{
				this.SetAttributeValue("licenseentitledby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("licenseentitledbyname")]
		public string licenseentitledbyName
		{
			get
			{
				if (this.FormattedValues.Contains("licenseentitledby"))
				{
					return this.FormattedValues["licenseentitledby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Additional metadata for this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("metadata")]
		public string Metadata
		{
			get
			{
				return this.GetAttributeValue<string>("metadata");
			}
			set
			{
				this.SetAttributeValue("metadata", value);
			}
		}
		
		/// <summary>
		/// Shows the mode of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mode")]
		public virtual workflow_mode? Mode
		{
			get
			{
				return ((workflow_mode?)(EntityOptionSetEnum.GetEnum(this, "mode")));
			}
			set
			{
				this.SetAttributeValue("mode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modename")]
		public string ModeName
		{
			get
			{
				if (this.FormattedValues.Contains("mode"))
				{
					return this.FormattedValues["mode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Type of the Modern Flow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modernflowtype")]
		public virtual workflow_modernflowtype? ModernFlowType
		{
			get
			{
				return ((workflow_modernflowtype?)(EntityOptionSetEnum.GetEnum(this, "modernflowtype")));
			}
			set
			{
				this.SetAttributeValue("modernflowtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modernflowtypename")]
		public string modernflowtypeName
		{
			get
			{
				if (this.FormattedValues.Contains("modernflowtype"))
				{
					return this.FormattedValues["modernflowtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the process was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Flow modify metadata used for telemetry, etc.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifymetadata")]
		public string ModifyMetadata
		{
			get
			{
				return this.GetAttributeValue<string>("modifymetadata");
			}
			set
			{
				this.SetAttributeValue("modifymetadata", value);
			}
		}
		
		/// <summary>
		/// Name of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the process is able to run as an on-demand process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ondemand")]
		public System.Nullable<bool> OnDemand
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ondemand");
			}
			set
			{
				this.SetAttributeValue("ondemand", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ondemandname")]
		public string OnDemandName
		{
			get
			{
				if (this.FormattedValues.Contains("ondemand"))
				{
					return this.FormattedValues["ondemand"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Outputs definition for this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outputs")]
		public string Outputs
		{
			get
			{
				return this.GetAttributeValue<string>("outputs");
			}
			set
			{
				this.SetAttributeValue("outputs", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit that owns the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the team who owns the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Unique identifier of the definition for process activation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentworkflowid")]
		public Microsoft.Xrm.Sdk.EntityReference ParentWorkflowId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentworkflowid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentworkflowidname")]
		public string ParentWorkflowIdName
		{
			get
			{
				if (this.FormattedValues.Contains("parentworkflowid"))
				{
					return this.FormattedValues["parentworkflowid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For Internal Use Only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("planverified")]
		public System.Nullable<bool> PlanVerified
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("planverified");
			}
			set
			{
				this.SetAttributeValue("planverified", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("planverifiedname")]
		public string planverifiedName
		{
			get
			{
				if (this.FormattedValues.Contains("planverified"))
				{
					return this.FormattedValues["planverified"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the plug-in type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("plugintypeid")]
		public Microsoft.Xrm.Sdk.EntityReference PluginTypeId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("plugintypeid");
			}
		}
		
		/// <summary>
		/// Primary entity for the process. The process can be associated for one or more SDK operations defined on the primary entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryentity")]
		public string PrimaryEntity
		{
			get
			{
				return this.GetAttributeValue<string>("primaryentity");
			}
			set
			{
				this.SetAttributeValue("primaryentity", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryentityname")]
		public string PrimaryEntityName
		{
			get
			{
				if (this.FormattedValues.Contains("primaryentity"))
				{
					return this.FormattedValues["primaryentity"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Type the business process flow order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processorder")]
		public System.Nullable<int> ProcessOrder
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("processorder");
			}
			set
			{
				this.SetAttributeValue("processorder", value);
			}
		}
		
		/// <summary>
		/// Contains the role assignment for the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processroleassignment")]
		public string ProcessRoleAssignment
		{
			get
			{
				return this.GetAttributeValue<string>("processroleassignment");
			}
			set
			{
				this.SetAttributeValue("processroleassignment", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated form for process trigger.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processtriggerformid")]
		public System.Nullable<System.Guid> ProcessTriggerFormId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processtriggerformid");
			}
			set
			{
				this.SetAttributeValue("processtriggerformid", value);
			}
		}
		
		/// <summary>
		/// Scope of the process trigger.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processtriggerscope")]
		public virtual processtrigger_scope? ProcessTriggerScope
		{
			get
			{
				return ((processtrigger_scope?)(EntityOptionSetEnum.GetEnum(this, "processtriggerscope")));
			}
			set
			{
				this.SetAttributeValue("processtriggerscope", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processtriggerscopename")]
		public string ProcessTriggerScopeName
		{
			get
			{
				if (this.FormattedValues.Contains("processtriggerscope"))
				{
					return this.FormattedValues["processtriggerscope"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Indicates the rank for order of execution for the synchronous workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rank")]
		public System.Nullable<int> Rank
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("rank");
			}
			set
			{
				this.SetAttributeValue("rank", value);
			}
		}
		
		/// <summary>
		/// The renderer type of Workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rendererobjecttypecode")]
		public string RendererObjectTypeCode
		{
			get
			{
				return this.GetAttributeValue<string>("rendererobjecttypecode");
			}
			set
			{
				this.SetAttributeValue("rendererobjecttypecode", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resourcecontainer")]
		public string ResourceContainer
		{
			get
			{
				return this.GetAttributeValue<string>("resourcecontainer");
			}
			set
			{
				this.SetAttributeValue("resourcecontainer", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resourceid")]
		public System.Nullable<System.Guid> ResourceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("resourceid");
			}
			set
			{
				this.SetAttributeValue("resourceid", value);
			}
		}
		
		/// <summary>
		/// Specifies the system user account under which a workflow executes.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runas")]
		public virtual workflow_runas? RunAs
		{
			get
			{
				return ((workflow_runas?)(EntityOptionSetEnum.GetEnum(this, "runas")));
			}
			set
			{
				this.SetAttributeValue("runas", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runasname")]
		public string RunAsName
		{
			get
			{
				if (this.FormattedValues.Contains("runas"))
				{
					return this.FormattedValues["runas"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Schema version for this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("schemaversion")]
		public string SchemaVersion
		{
			get
			{
				return this.GetAttributeValue<string>("schemaversion");
			}
			set
			{
				this.SetAttributeValue("schemaversion", value);
			}
		}
		
		/// <summary>
		/// Scope of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("scope")]
		public virtual workflow_scope? Scope
		{
			get
			{
				return ((workflow_scope?)(EntityOptionSetEnum.GetEnum(this, "scope")));
			}
			set
			{
				this.SetAttributeValue("scope", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("scopename")]
		public string ScopeName
		{
			get
			{
				if (this.FormattedValues.Contains("scope"))
				{
					return this.FormattedValues["scope"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the SDK Message associated with this workflow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdkmessageid")]
		public Microsoft.Xrm.Sdk.EntityReference SdkMessageId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdkmessageid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual workflow_statecode? StateCode
		{
			get
			{
				return ((workflow_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual workflow_statuscode? StatusCode
		{
			get
			{
				return ((workflow_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Indicates whether the process can be included in other processes as a child process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subprocess")]
		public System.Nullable<bool> Subprocess
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("subprocess");
			}
			set
			{
				this.SetAttributeValue("subprocess", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subprocessname")]
		public string SubprocessName
		{
			get
			{
				if (this.FormattedValues.Contains("subprocess"))
				{
					return this.FormattedValues["subprocess"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("suspensionreasondetails")]
		public string SuspensionReasonDetails
		{
			get
			{
				return this.GetAttributeValue<string>("suspensionreasondetails");
			}
			set
			{
				this.SetAttributeValue("suspensionreasondetails", value);
			}
		}
		
		/// <summary>
		/// Select whether synchronous workflow failures will be saved to log files.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("syncworkflowlogonfailure")]
		public System.Nullable<bool> SyncWorkflowLogOnFailure
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("syncworkflowlogonfailure");
			}
			set
			{
				this.SetAttributeValue("syncworkflowlogonfailure", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("syncworkflowlogonfailurename")]
		public string SyncWorkflowLogOnFailureName
		{
			get
			{
				if (this.FormattedValues.Contains("syncworkflowlogonfailure"))
				{
					return this.FormattedValues["syncworkflowlogonfailure"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The throttling behavior type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("throttlingbehavior")]
		public virtual workflow_throttlingbehaviortype? ThrottlingBehavior
		{
			get
			{
				return ((workflow_throttlingbehaviortype?)(EntityOptionSetEnum.GetEnum(this, "throttlingbehavior")));
			}
			set
			{
				this.SetAttributeValue("throttlingbehavior", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("throttlingbehaviorname")]
		public string throttlingbehaviorName
		{
			get
			{
				if (this.FormattedValues.Contains("throttlingbehavior"))
				{
					return this.FormattedValues["throttlingbehavior"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Indicates whether the process will be triggered when the primary entity is created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggeroncreate")]
		public System.Nullable<bool> TriggerOnCreate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("triggeroncreate");
			}
			set
			{
				this.SetAttributeValue("triggeroncreate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggeroncreatename")]
		public string TriggerOnCreateName
		{
			get
			{
				if (this.FormattedValues.Contains("triggeroncreate"))
				{
					return this.FormattedValues["triggeroncreate"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Indicates whether the process will be triggered on deletion of the primary entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggerondelete")]
		public System.Nullable<bool> TriggerOnDelete
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("triggerondelete");
			}
			set
			{
				this.SetAttributeValue("triggerondelete", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggerondeletename")]
		public string TriggerOnDeleteName
		{
			get
			{
				if (this.FormattedValues.Contains("triggerondelete"))
				{
					return this.FormattedValues["triggerondelete"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Attributes that trigger the process when updated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggeronupdateattributelist")]
		public string TriggerOnUpdateAttributeList
		{
			get
			{
				return this.GetAttributeValue<string>("triggeronupdateattributelist");
			}
			set
			{
				this.SetAttributeValue("triggeronupdateattributelist", value);
			}
		}
		
		/// <summary>
		/// For Internal Use Only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trustedaccess")]
		public System.Nullable<bool> TrustedAccess
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("trustedaccess");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trustedaccessname")]
		public string trustedaccessName
		{
			get
			{
				if (this.FormattedValues.Contains("trustedaccess"))
				{
					return this.FormattedValues["trustedaccess"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Type of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("type")]
		public virtual workflow_type? Type
		{
			get
			{
				return ((workflow_type?)(EntityOptionSetEnum.GetEnum(this, "type")));
			}
			set
			{
				this.SetAttributeValue("type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("typename")]
		public string TypeName
		{
			get
			{
				if (this.FormattedValues.Contains("type"))
				{
					return this.FormattedValues["type"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uidata")]
		public string UIData
		{
			get
			{
				return this.GetAttributeValue<string>("uidata");
			}
		}
		
		/// <summary>
		/// Type of the UI Flow process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uiflowtype")]
		public virtual workflow_uiflowtype? UIFlowType
		{
			get
			{
				return ((workflow_uiflowtype?)(EntityOptionSetEnum.GetEnum(this, "uiflowtype")));
			}
			set
			{
				this.SetAttributeValue("uiflowtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uiflowtypename")]
		public string UIFlowTypeName
		{
			get
			{
				if (this.FormattedValues.Contains("uiflowtype"))
				{
					return this.FormattedValues["uiflowtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique name of the process
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
		public string UniqueName
		{
			get
			{
				return this.GetAttributeValue<string>("uniquename");
			}
			set
			{
				this.SetAttributeValue("uniquename", value);
			}
		}
		
		/// <summary>
		/// Select the stage a process will be triggered on update.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("updatestage")]
		public virtual workflow_stage? UpdateStage
		{
			get
			{
				return ((workflow_stage?)(EntityOptionSetEnum.GetEnum(this, "updatestage")));
			}
			set
			{
				this.SetAttributeValue("updatestage", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("updatestagename")]
		public string UpdateStageName
		{
			get
			{
				if (this.FormattedValues.Contains("updatestage"))
				{
					return this.FormattedValues["updatestage"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
		public System.Nullable<System.Guid> WorkflowId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("workflowid");
			}
			set
			{
				this.SetAttributeValue("workflowid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.WorkflowId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowidunique")]
		public System.Nullable<System.Guid> WorkflowIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("workflowidunique");
			}
		}
		
		/// <summary>
		/// XAML that defines the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("xaml")]
		public string Xaml
		{
			get
			{
				return this.GetAttributeValue<string>("xaml");
			}
			set
			{
				this.SetAttributeValue("xaml", value);
			}
		}
		
		/// <summary>
		/// 1:N lk_asyncoperation_workflowactivationid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_asyncoperation_workflowactivationid")]
		public System.Collections.Generic.IEnumerable<DataverseEntities.AsyncOperation> lk_asyncoperation_workflowactivationid
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.AsyncOperation>("lk_asyncoperation_workflowactivationid", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.AsyncOperation>("lk_asyncoperation_workflowactivationid", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_processsession_processid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_processsession_processid")]
		public System.Collections.Generic.IEnumerable<DataverseEntities.ProcessSession> lk_processsession_processid
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.ProcessSession>("lk_processsession_processid", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.ProcessSession>("lk_processsession_processid", null, value);
			}
		}
		
		/// <summary>
		/// 1:N process_processstage
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("process_processstage")]
		public System.Collections.Generic.IEnumerable<DataverseEntities.ProcessStage> process_processstage
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.ProcessStage>("process_processstage", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.ProcessStage>("process_processstage", null, value);
			}
		}
		
		/// <summary>
		/// 1:N workflow_active_workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DataverseEntities.Workflow> Referencedworkflow_active_workflow
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.Workflow>("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.Workflow>("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N Workflow_Annotation
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Workflow_Annotation")]
		public System.Collections.Generic.IEnumerable<DataverseEntities.Annotation> Workflow_Annotation
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.Annotation>("Workflow_Annotation", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.Annotation>("Workflow_Annotation", null, value);
			}
		}
		
		/// <summary>
		/// 1:N Workflow_licenseentitledby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Workflow_licenseentitledby", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DataverseEntities.Workflow> ReferencedWorkflow_licenseentitledby
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.Workflow>("Workflow_licenseentitledby", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.Workflow>("Workflow_licenseentitledby", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N workflow_parent_workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DataverseEntities.Workflow> Referencedworkflow_parent_workflow
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.Workflow>("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.Workflow>("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_workflow")]
		public DataverseEntities.BusinessUnit business_unit_workflow
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.BusinessUnit>("business_unit_workflow", null);
			}
		}
		
		/// <summary>
		/// N:1 system_user_workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("system_user_workflow")]
		public DataverseEntities.SystemUser system_user_workflow
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("system_user_workflow", null);
			}
		}
		
		/// <summary>
		/// N:1 team_workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_workflow")]
		public DataverseEntities.Team team_workflow
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Team>("team_workflow", null);
			}
		}
		
		/// <summary>
		/// N:1 workflow_active_workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activeworkflowid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DataverseEntities.Workflow Referencingworkflow_active_workflow
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Workflow>("workflow_active_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
		
		/// <summary>
		/// N:1 workflow_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_createdby")]
		public DataverseEntities.SystemUser workflow_createdby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("workflow_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 workflow_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_createdonbehalfby")]
		public DataverseEntities.SystemUser workflow_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("workflow_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 Workflow_licenseentitledby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("licenseentitledby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Workflow_licenseentitledby", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DataverseEntities.Workflow ReferencingWorkflow_licenseentitledby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Workflow>("Workflow_licenseentitledby", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.Workflow>("Workflow_licenseentitledby", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			}
		}
		
		/// <summary>
		/// N:1 workflow_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_modifiedby")]
		public DataverseEntities.SystemUser workflow_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("workflow_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 workflow_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_modifiedonbehalfby")]
		public DataverseEntities.SystemUser workflow_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.SystemUser>("workflow_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 workflow_parent_workflow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentworkflowid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DataverseEntities.Workflow Referencingworkflow_parent_workflow
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.Workflow>("workflow_parent_workflow", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
	}
}
#pragma warning restore CS1591
