name: CI Pull Request (2x)

on:
  pull_request:
    branches: [ 2x-dev ]

jobs:
  build-windows:
    strategy:
      fail-fast: false 
      matrix: 
        configuration: ['FAKE_XRM_EASY_9', 'FAKE_XRM_EASY_365', 'FAKE_XRM_EASY_2016','FAKE_XRM_EASY_2015','FAKE_XRM_EASY_2013','FAKE_XRM_EASY']

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core for Actual Source
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
 
    - name: Disable local packages feed
      run: dotnet nuget disable source "local-packages"

    - name: Enable GitHub packages feed
      run: dotnet nuget enable source github
      
    - name: Build
      run: pwsh ./build.ps1 -configuration ${{matrix.configuration}} -targetFrameworks 'all'
      env: 
        NUGET_USERNAME: DynamicsValue
        NUGET_TOKEN: ${{ secrets.PACKAGES_TOKEN }} 

  